version: "3.3"
volumes:
  db_data: { }
services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=flask:8000
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - "80:80"
    depends_on:
      - flask
  mongo:
    image: mongo:4.4
    volumes:
      - ./db_data:/data/db/
    ports:
      - "27017:27017"
    restart: always
  flask:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: gunicorn run:app -b 0.0.0.0:8000 --reload
    restart: always